# Generated by Django 5.2.5 on 2025-08-31 09:55
from django.db import migrations
from django.utils.text import slugify

def create_default_categories(apps, schema_editor):
    """
    Creates a set of default product categories in the database.
    """
    ProductCategory = apps.get_model('tasks', 'ProductCategory')

    categories = [
        {
            'name': 'Coffee Related',
            'name_fa': 'محصولات قهوه',
            'description': 'Coffee beans, coffee makers Liberals, and coffee accessories',
            'order': 1
        },
        {
            'name': 'Seeds',
            'name_fa': 'دانه‌ها',
            'description': 'Various types of seeds for planting and consumption',
            'order': 2
        },
        {
            'name': 'Spices',
            'name_fa': 'ادویه‌جات',
            'description': 'Spices and seasonings from around the world',
            'order': 3
        },
        {
            'name': 'Nuts',
            'name_fa': 'آجیل',
            'description': 'Various types of nuts and dried fruits',
            'order': 4
        },
        {
            'name': 'Confectionery Products',
            'name_fa': 'محصولات قنادی',
            'description': 'Confectionery products',
            'order': 5
        }
    ]

    for cat_data in categories:
        # Automatically generate the slug from the English name
        cat_data['slug'] = slugify(cat_data['name'])

        # Create the category if it doesn't already exist
        ProductCategory.objects.get_or_create(
            slug=cat_data['slug'],
            defaults=cat_data
        )

def remove_default_categories(apps, schema_editor):
    """
    Removes the default categories. This makes the migration reversible.
    """
    ProductCategory = apps.get_model('tasks', 'ProductCategory')
    slugs = [slugify(cat['name']) for cat in create_default_categories.categories]
    ProductCategory.objects.filter(slug__in=slugs).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]

# This is a helper to make the reverse function work without duplicating the data
create_default_categories.categories = [
    {'name': 'Coffee Related'},
    {'name': 'Seeds'},
    {'name': 'Spices'},
    {'name': 'Nuts'},
    {'name': 'Confectionery Products'}
]
