# Generated by Django 5.2 on 2025-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comment',
            new_name='customer_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('pre_invoice', 'Pre-Invoice'), ('final_invoice', 'Final Invoice')], default='pre_invoice', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate as percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_comment',
            field=models.TextField(blank=True, help_text="Admin's pricing notes", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, help_text="Customer's initial request/comments", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pricing_date',
            field=models.DateTimeField(blank=True, help_text='When admin provided pricing', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quoted_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total quoted by admin', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about pricing/availability', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Special requirements from customer', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='final_quantity',
            field=models.IntegerField(default=0, help_text='Final quantity confirmed by admin'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quoted_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price quoted by admin', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='requested_quantity',
            field=models.IntegerField(default=1, help_text='Quantity requested by customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base price for reference', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to product images', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_pricing', 'Pending Pricing'), ('waiting_customer_approval', 'Waiting Customer Approval'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_pricing', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet Payment'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check')], max_length=50),
        ),
    ]
