# Generated by Django 5.2.4 on 2025-07-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_comment_order_customer_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
