# Generated by Django 5.2.4 on 2025-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20250809_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reset_token',
            field=models.CharField(blank=True, help_text='Password reset token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, help_text='When the reset token expires', null=True),
        ),
    ]
