# Generated by Django 5.2.4 on 2025-08-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_customer_reset_token_customer_reset_token_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='When password was last changed', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reset_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of reset attempts in current window'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reset_attempts_reset_at',
            field=models.DateTimeField(blank=True, help_text='When reset attempts counter resets', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reset_token',
            field=models.CharField(blank=True, db_index=True, help_text='Password reset token', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the reset token expires', null=True),
        ),
    ]
