# Generated by Django 5.2.4 on 2025-08-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0004_customer_account_locked_until_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['reset_token'], name='customers_reset_t_a9ff1a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['reset_token_expires'], name='customers_reset_t_375d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email', 'is_active'], name='customers_email_a3d366_idx'),
        ),
    ]
