# Generated by Django 5.2.4 on 2025-07-15 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_customer_groups_customer_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_feedback_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='priced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
