# Generated by Django 5.2.4 on 2025-08-17 07:47

# Generated by Django 4.2 on 2025-08-17

from django.db import migrations


def update_nuts_category(apps, schema_editor):
    """
    Updates the Persian name for the Nuts category from 'آجیل' to 'آجیل و خشکبار'.
    """
    ProductCategory = apps.get_model('tasks', 'ProductCategory')

    try:
        nuts_category = ProductCategory.objects.get(slug='nuts')
        nuts_category.name_fa = 'آجیل و خشکبار'
        nuts_category.save()
        print(f"Updated Nuts category Persian name to: {nuts_category.name_fa}")
    except ProductCategory.DoesNotExist:
        print("Nuts category not found - skipping update")


def reverse_nuts_category(apps, schema_editor):
    """
    Reverts the Persian name back to the original 'آجیل'.
    """
    ProductCategory = apps.get_model('tasks', 'ProductCategory')

    try:
        nuts_category = ProductCategory.objects.get(slug='nuts')
        nuts_category.name_fa = 'آجیل'
        nuts_category.save()
        print(f"Reverted Nuts category Persian name to: {nuts_category.name_fa}")
    except ProductCategory.DoesNotExist:
        print("Nuts category not found - skipping revert")


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0005_customer_customers_reset_t_a9ff1a_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(update_nuts_category, reverse_nuts_category),
    ]
