# Generated by Django 5.2.4 on 2025-07-20 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_customer_options_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company_info', models.JSONField(default=dict, help_text='Store company details')),
                ('font_family', models.CharField(default='Vazir', max_length=50)),
                ('page_size', models.CharField(default='A4', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
                'db_table': 'invoice_templates',
            },
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who completed the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(blank=True, help_text='When order was completed', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_pricing', 'Pending Pricing'), ('waiting_customer_approval', 'Waiting Customer Approval'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_pricing', max_length=30),
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('order_submitted', 'Order Submitted'), ('pricing_ready', 'Pricing Ready'), ('order_confirmed', 'Order Confirmed'), ('order_rejected', 'Order Rejected'), ('order_completed', 'Order Completed')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.order')),
            ],
            options={
                'db_table': 'email_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=50)),
                ('section_title', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_table', models.BooleanField(default=False, help_text='True for items table')),
                ('table_columns', models.JSONField(default=list, help_text='Column definitions for tables')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tasks.invoicetemplate')),
            ],
            options={
                'db_table': 'invoice_sections',
                'ordering': ['display_order'],
                'unique_together': {('template', 'section_key')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text="e.g., 'customer_name', 'total_amount'", max_length=50)),
                ('field_label', models.CharField(help_text="e.g., 'نام مشتری', 'مبلغ کل'", max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('price', 'Price'), ('date', 'Date'), ('email', 'Email')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('section', models.CharField(help_text="e.g., 'company', 'customer', 'items', 'totals'", max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tasks.invoicetemplate')),
            ],
            options={
                'db_table': 'invoice_template_fields',
                'ordering': ['section', 'display_order'],
                'unique_together': {('template', 'field_key')},
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
