# Generated by Django 5.2.4 on 2025-07-21 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_invoicetemplate_remove_wallet_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='quoted_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total quoted by admin', max_digits=12),
        ),
    ]
