# Generated by Django 5.2.4 on 2025-07-22 15:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_invoice_payable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dealer_code',
            field=models.CharField(blank=True, help_text='Unique dealer code', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dealer_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_dealer',
            field=models.BooleanField(default=False, help_text='Is this user a dealer?'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer assigned to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='dealer_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When dealer was assigned', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dealer_notes',
            field=models.TextField(blank=True, help_text='Notes from assigned dealer', null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='email_type',
            field=models.CharField(choices=[('order_submitted', 'Order Submitted'), ('pricing_ready', 'Pricing Ready'), ('order_confirmed', 'Order Confirmed'), ('order_rejected', 'Order Rejected'), ('order_completed', 'Order Completed'), ('dealer_assigned', 'Dealer Assigned')], max_length=20),
        ),
        migrations.CreateModel(
            name='DealerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission percentage at time of completion', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Calculated commission amount', max_digits=10)),
                ('order_total', models.DecimalField(decimal_places=2, help_text='Order total at time of completion', max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='tasks.order')),
            ],
            options={
                'db_table': 'dealer_commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_created', 'Order Created'), ('pricing_submitted', 'Pricing Submitted'), ('customer_approved', 'Customer Approved'), ('customer_rejected', 'Customer Rejected'), ('order_completed', 'Order Completed'), ('dealer_assigned', 'Dealer Assigned'), ('dealer_removed', 'Dealer Removed'), ('dealer_notes_updated', 'Dealer Notes Updated')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.order')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
