# Generated by Django 5.2.4 on 2025-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_customer_dealer_code_customer_dealer_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Custom commission rate for this order (overrides dealer's default rate)", max_digits=5, null=True),
        ),
    ]
