# Generated by Django 5.2.4 on 2025-07-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_product_image_url_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured product'),
        ),
        migrations.AddField(
            model_name='shipmentannouncement',
            name='origin_country',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ShipmentAnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shipments/images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.shipmentannouncement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
