# Generated by Django 5.2.4 on 2025-07-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_product_is_featured_and_more'),
        ('tasks', '0014_auto_20250725_1817'),
    ]

    operations = [
    ]
