# Generated by Django 5.2.4 on 2025-07-25 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_merge_20250725_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name_fa',
            field=models.CharField(blank=True, help_text='Persian name', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tasks.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(help_text='English name', max_length=100),
        ),
    ]
