# Generated by Django 5.2.4 on 2025-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_productcategory_name_fa_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, help_text='Country/place of origin', max_length=100, null=True),
        ),
    ]
