# Generated by Django 5.2.4 on 2025-07-25 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_product_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentannouncementimage',
            options={'ordering': ['order'], 'verbose_name': 'Shipment Announcement Image', 'verbose_name_plural': 'Shipment Announcement Images'},
        ),
        migrations.AddField(
            model_name='shipmentannouncement',
            name='estimated_arrival',
            field=models.DateField(blank=True, help_text='Estimated arrival date', null=True),
        ),
        migrations.AddField(
            model_name='shipmentannouncement',
            name='product_categories',
            field=models.CharField(blank=True, help_text='Categories of products in this shipment', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipmentannouncement',
            name='shipment_date',
            field=models.DateField(blank=True, help_text='Date when shipment was sent', null=True),
        ),
        migrations.AddField(
            model_name='shipmentannouncement',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times viewed'),
        ),
        migrations.AlterField(
            model_name='shipmentannouncement',
            name='created_by',
            field=models.ForeignKey(help_text='Admin who created this announcement', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipmentannouncement',
            name='image',
            field=models.ImageField(blank=True, help_text='Main photo of packaging/container', null=True, upload_to='shipments/'),
        ),
        migrations.AlterField(
            model_name='shipmentannouncement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this announcement active?'),
        ),
        migrations.AlterField(
            model_name='shipmentannouncement',
            name='title',
            field=models.CharField(help_text='Title of the shipment announcement', max_length=200),
        ),
        migrations.AlterField(
            model_name='shipmentannouncementimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterModelTable(
            name='shipmentannouncementimage',
            table='shipment_announcement_images',
        ),
    ]
