# Generated by Django 5.2.4 on 2025-07-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_add_shipment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='announcement',
            field=models.ForeignKey(blank=True, help_text='Related announcement for announcement emails', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.shipmentannouncement'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer who received the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='email_type',
            field=models.CharField(choices=[('order_submitted', 'Order Submitted'), ('pricing_ready', 'Pricing Ready'), ('order_confirmed', 'Order Confirmed'), ('order_rejected', 'Order Rejected'), ('order_completed', 'Order Completed'), ('dealer_assigned', 'Dealer Assigned'), ('dealer_assigned', 'Dealer Assigned'), ('dealer_removed', 'Dealer Removed'), ('new_arrival_customer', 'New Arrival - Customer'), ('new_arrival_dealer', 'New Arrival - Dealer'), ('announcement_updated', 'Announcement Updated')], max_length=20),
        ),
    ]
