# Generated by Django 5.2.4 on 2025-07-28 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_emailnotification_announcement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_type', models.CharField(choices=[('order_submitted', 'Order Submitted'), ('pricing_ready', 'Pricing Ready'), ('order_confirmed', 'Order Confirmed'), ('order_rejected', 'Order Rejected'), ('order_completed', 'Order Completed'), ('dealer_assigned', 'Dealer Assigned'), ('new_arrival_customer', 'New Arrival - Customer'), ('new_arrival_dealer', 'New Arrival - Dealer'), ('commission_paid', 'Commission Paid'), ('otp', 'OTP Verification'), ('general', 'General Notification'), ('test', 'Test Message'), ('bulk', 'Bulk Message')], default='general', max_length=30)),
                ('recipient_phone', models.CharField(help_text='Phone number(s) SMS was sent to', max_length=20)),
                ('message', models.TextField(help_text='SMS message content', max_length=500)),
                ('is_successful', models.BooleanField(default=False)),
                ('kavenegar_response', models.TextField(blank=True, help_text='Kavenegar API response', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='SMS cost (if provided by API)', max_digits=10, null=True)),
                ('message_id', models.CharField(blank=True, help_text='Kavenegar message ID', max_length=100, null=True)),
                ('announcement', models.ForeignKey(blank=True, help_text='Related announcement (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='tasks.shipmentannouncement')),
                ('dealer', models.ForeignKey(blank=True, help_text='Dealer who received the SMS (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_sms_notifications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Related order (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='tasks.order')),
            ],
            options={
                'verbose_name': 'SMS Notification',
                'verbose_name_plural': 'SMS Notifications',
                'db_table': 'sms_notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
