# Generated by Django 5.2.4 on 2025-07-29 10:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_smsnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quoted_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price quoted by admin', max_digits=15),
        ),
    ]
