# Generated by Django 5.2.4 on 2025-07-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_orderitem_quoted_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth user ID', max_length=100, null=True, unique=True),
        ),
    ]
