# Generated by Django 5.2.4 on 2025-07-31 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_customer_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Admin notes about payment verification', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text='Payment receipt or cheque image', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When payment receipt was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Admin verified the payment receipt'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When payment was verified by admin', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_pricing', 'Pending Pricing'), ('waiting_customer_approval', 'Waiting Customer Approval'), ('confirmed', 'Confirmed'), ('waiting_payment', 'Waiting Payment Receipt'), ('payment_uploaded', 'Payment Receipt Uploaded'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_pricing', max_length=30),
        ),
    ]
