# Generated by Django 5.2.4 on 2025-07-31 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_order_payment_notes_order_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_payment_receipts',
            field=models.BooleanField(default=False, help_text='True if order has any payment receipts uploaded'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text='Legacy single payment receipt (deprecated)', null=True, upload_to='payment_receipts/'),
        ),
        migrations.CreateModel(
            name='OrderPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(help_text='Payment receipt image or PDF', upload_to='payment_receipts/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], help_text='Type of uploaded file', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='tasks.order')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this receipt', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_payment_receipts',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
