# Generated by Django 5.2.4 on 2025-08-01 17:05

import django.db.models.deletion
import django.utils.timezone
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_order_has_payment_receipts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpaymentreceipt',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Payment Receipt', 'verbose_name_plural': 'Payment Receipts'},
        ),
        migrations.AddField(
            model_name='orderpaymentreceipt',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When this receipt was verified', null=True),
        ),
        migrations.AddField(
            model_name='orderpaymentreceipt',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('pricing_submitted', 'Pricing Submitted'), ('customer_approved', 'Customer Approved'), ('customer_rejected', 'Customer Rejected'), ('order_completed', 'Order Completed'), ('dealer_assigned', 'Dealer Assigned'), ('dealer_removed', 'Dealer Removed'), ('dealer_notes_updated', 'Dealer Notes Updated'), ('payment_receipts_uploaded', 'Payment Receipts Uploaded'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderpaymentreceipt',
            name='admin_notes',
            field=models.TextField(blank=True, default=django.utils.timezone.now, help_text='Admin notes about this receipt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpaymentreceipt',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this receipt has been verified by admin'),
        ),
        migrations.AlterField(
            model_name='orderpaymentreceipt',
            name='receipt_file',
            field=models.FileField(help_text='Payment receipt file (image or PDF)', upload_to=tasks.models.OrderPaymentReceipt.receipt_upload_path),
        ),
    ]
