# Generated by Django 5.2.4 on 2025-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_alter_orderpaymentreceipt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_invoice_type',
            field=models.CharField(choices=[('official', 'Official Invoice'), ('unofficial', 'Unofficial Invoice')], default='unofficial', help_text='Business type of invoice - Official (with tax) or Unofficial (without tax)', max_length=15),
        ),
    ]
