# Generated by Django 5.2.4 on 2025-08-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_add_business_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='complete_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='economic_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='business_invoice_type',
            field=models.CharField(choices=[('official', 'فاکتور رسمی'), ('unofficial', 'فاکتور غیررسمی')], default='unofficial', help_text='Business type of invoice - Official (with tax) or Unofficial (without tax)', max_length=15),
        ),
    ]
