# Generated by Django 5.2.4 on 2025-08-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_customer_city_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_type',
            new_name='business_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_invoice_type',
            field=models.CharField(choices=[('unofficial', 'غیررسمی'), ('official', 'رسمی')], default='unofficial', max_length=20, verbose_name='نوع فاکتور ترجیحی'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره ثبت شرکت'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره مالیاتی'),
        ),
    ]
