# Generated by Django 5.2.4 on 2025-08-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_rename_customer_type_customer_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='shipmentannouncement',
            name='images',
        ),
        migrations.RemoveField(
            model_name='shipmentannouncementimage',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary product images', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Tax rate for this product as percentage', max_digits=5, verbose_name='Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='', upload_to='products/additional/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentannouncement',
            name='image',
            field=models.ImageField(blank=True, help_text='Main photo of packaging/container', null=True, upload_to='shipments/'),
        ),
        migrations.AddField(
            model_name='shipmentannouncementimage',
            name='image',
            field=models.ImageField(default='', upload_to='shipments/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_invoice_type',
            field=models.CharField(choices=[('unofficial', 'بدون مالیات'), ('official', 'رسمی')], default='unofficial', max_length=20, verbose_name='نوع فاکتور ترجیحی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='business_invoice_type',
            field=models.CharField(choices=[('official', 'فاکتور رسمی'), ('unofficial', 'فاکتور شخصی')], default='unofficial', help_text='Business type of invoice - Official (with tax) or Unofficial (without tax)', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('pricing_submitted', 'Pricing Submitted'), ('customer_approved', 'Customer Approved'), ('customer_rejected', 'Customer Rejected'), ('order_completed', 'Order Completed'), ('dealer_assigned', 'Dealer Assigned'), ('dealer_removed', 'Dealer Removed'), ('dealer_notes_updated', 'Dealer Notes Updated'), ('payment_receipts_uploaded', 'Payment Receipts Uploaded'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('invoice_type_changed', 'Invoice Type Changed'), ('pre_invoice_generated', 'Pre-Invoice Generated'), ('final_invoice_generated', 'Final Invoice Generated')], max_length=50),
        ),
    ]
