# Generated by Django 5.2.4 on 2025-08-07 21:08

import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_add_product_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='email_type',
            field=models.CharField(choices=[('order_submitted', 'Order Submitted'), ('pricing_ready', 'Pricing Ready'), ('order_confirmed', 'Order Confirmed'), ('order_rejected', 'Order Rejected'), ('order_completed', 'Order Completed'), ('dealer_assigned', 'Dealer Assigned'), ('dealer_removed', 'Dealer Removed'), ('new_arrival_customer', 'New Arrival - Customer'), ('new_arrival_dealer', 'New Arrival - Dealer'), ('announcement_updated', 'Announcement Updated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.order'),
        ),
        migrations.AlterField(
            model_name='orderpaymentreceipt',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], help_text='Type of uploaded file', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderpaymentreceipt',
            name='receipt_file',
            field=models.FileField(help_text='Payment receipt file (image or PDF)', upload_to=tasks.models.OrderPaymentReceipt.receipt_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary product image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipmentannouncementimage',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='tasks.shipmentannouncement'),
        ),
    ]
